### ISSUE TITLE
Docker-compose file

### ISSUE THREAD

**Issue by lambarena** [beeworking/voyant#10]
I am getting the following error when I run docker-compose:

`envsubst: error while reading "standard input": Is a directory`

Which points to this line in docker-compose.yml:
`command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"`

I tried removing the envsubst line completely and manually modify the nginx conf to 0.0.0.0:8000 but that didn't work.

Here's the docker-compose.yml:

```
web:
  image: nginx:latest
  ports:
    - "8080:8080"
  volumes:
    - nginx.template:/etc/nginx/conf.d/nginx.template
    - ./clients/web/:/html/
  links:
    - api
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

api:
  build: .
  volumes:
    - .:/app/
  links:
    - db

db:
  image: mongo:3.2
  volumes:
   - ./volume/db:/data/db
```

Reference:
[Issue #496](https://github.com/docker-library/docs/issues/496)
